spring:
  application:
    name: wechat
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://120.76.100.173?characterEncoding=UTF-8
    username: root
    password: Aa664490254

  gson:
    disable-html-escaping: true

  mail:
    host: smtp.yeah.net
    port: 465
    password: KOLXLPATXBOOXILT
    username: safety_report@yeah.net
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true


pool:
  core-pool-size: 10
  max-pool-size: 100
  keep-alive-seconds: 300
  queue-capacity: 150

wechat:
  wx-token: Jeffrey
  wx-app-id: wx1ea22b7747f6a666 # 测试号
  wx-app-secret: 80819212b09ec541339f68533bbeb348 # 测试号
  wx-customer-url: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token={token}
  wx-get-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type={grant_type}&appid={appid}&secret={secret}



email:
  email-from: safety_report@yeah.net
  email-to: jeffrey2971@outlook.com
  email-port: 465
  email-c-c: 664490254@qq.com
  email-pass-code: KOLXLPATXBOOXILT

baidu:
  baidu-transaction-app-id: 20200709000515966 # appid
  baidu-transaction-app-key: gkV0xq2Wz5zgCgbft68b # appkey
  erase-none: 0 # 不擦除
  erase-full: 1 # 全屏擦除
  erase-block: 2 # 区块擦除
  paste-none: 0 # 不贴合
  paste-full: 1 # 全屏贴合
  paste-block: 2 # 区块贴合
  close: 0 # 关闭填充
  auto: auto # 自动检测
  zh: zh # 中文
  en: en # 英语
  jp: jp # 日语
  kor: kor # 韩语
  fra: fra # 法语
  spa: spa # 西班牙语
  ru: ru # 俄语
  pt: pt # 葡萄牙语
  de: de # 德语
  it: it # 意大利语
  dan: dan # 丹麦语
  nl: nl # 荷兰语
  may: may # 马来语
  swe: swe # 瑞典语
  id: id # 印尼语
  pl: pl # 波兰语
  rom: rom # 罗马尼亚语
  tr: tr # 土耳其语
  el: el # 希腊语
  hu: hu # 匈牙利语
  req-url: https://fanyi-api.baidu.com/api/trans/sdk/picture
  file-content-type: mutipart/form-data

cli:
  cli-style-id: QR_LIMIT_STR_SCENE
  cli-action-type: 5BDCCgromMMhMHYqLtJUP68

global:
  frequency-threshold: 15
  blackUser-wait-time: 300000
  frequency-check-time: 15000


domain:
  # domain: http://jeffrey2971.top
  domain: http://hap5rq.natappfree.cc

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true