spring:
  application:
    name: wechat
  main:
    allow-bean-definition-overriding: true


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://666/wx_public_account?characterEncoding=UTF-8
    username: 666
    password: 666

    druid:
      stat-view-servlet:
        enabled: true
        # 允许清空统计数据
        reset-enable: true
        # 为 Druid 监控配置访问权限(配置访问监控信息的用户与密码)
        login-username: 666
        login-password: 666
      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js, *.gif, *.png, *.jpg, *.css, *.ico, /druid/*'
      filters:
        stat, wall
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      aop-patterns: com.jeffrey.wechat


  gson:
    disable-html-escaping: true

  mail:
    host: smtp.yeah.net
    port: 465
    password: 666
    username: 666
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true


pool:
  core-pool-size: 10
  max-pool-size: 100
  keep-alive-seconds: 300
  queue-capacity: 150

wechat:
  wx-token: 666
  wx-app-id: 666 # 测试号
  wx-app-secret: 666 # 测试号
  wx-customer-url: https://api.weixin.qq.com/cgi-bin/message/custom/send?access_token={token}
  wx-get-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type={grant_type}&appid={appid}&secret={secret}
  wx-get-user-info-url: https://api.weixin.qq.com/cgi-bin/user/info?access_token={token}&openid={openid}&lang={lang}
  wx-get-qr-code-url: https://api.weixin.qq.com/cgi-bin/qrcode/create?access_token={token}
  wx-upload-media-data-url: https://api.weixin.qq.com/cgi-bin/material/add_material?access_token={token}&type={type}
  wx-delete-media-data-url: https://api.weixin.qq.com/cgi-bin/material/del_material?access_token={token}
  wx-create-menu-url: https://api.weixin.qq.com/cgi-bin/menu/create?access_token={token}
  wx-get-user-open-id-list: https://api.weixin.qq.com/cgi-bin/user/get?access_token={token}&next_openid={next_openid}
  wx-delete-menu-url: https://api.weixin.qq.com/cgi-bin/menu/delete?access_token={token}
  wx-show-use-url: https://mp.weixin.qq.com/s/3ypEPH04Q6CN7SS7CwGFXQ
  wx-get-batch-user-open-id-list: https://api.weixin.qq.com/cgi-bin/user/info/batchget?access_token={token}
  wx-share-threshold: 3
  wx-day-can-use: 5

  thank-keywords:
    - 谢
    - 谢谢
    - 感谢
    - 谢啦
    - 感激
    - 感激不尽
    - 非常感谢
    - thank
    - thanks
    - thankyou
    - thank you

email:
  email-from: 666 # 发送方
  email-to: 666 # 接收方
  email-port: 465 # yeah.net smtp 端口
  email-c-c: 666 # 抄送地址
  email-pass-code: 666 # 发送方校验码

baidu:
  baidu-transaction-app-id: 666 # appid
  baidu-transaction-app-key: 666 # appkey
  erase-none: 0 # 不擦除
  erase-full: 1 # 全屏擦除
  erase-block: 2 # 区块擦除
  paste-none: 0 # 不贴合
  paste-full: 1 # 全屏贴合
  paste-block: 2 # 区块贴合
  close: 0 # 关闭填充
  version: 3 # 版本，固定值
  mac: mac # 固定值
  cuid: APICUID # 固定值
  auto: auto # 自动检测
  zh: zh # 中文
  en: en # 英语
  jp: jp # 日语
  kor: kor # 韩语
  fra: fra # 法语
  spa: spa # 西班牙语
  ru: ru # 俄语
  pt: pt # 葡萄牙语
  de: de # 德语
  it: it # 意大利语
  dan: dan # 丹麦语
  nl: nl # 荷兰语
  may: may # 马来语
  swe: swe # 瑞典语
  id: id # 印尼语
  pl: pl # 波兰语
  rom: rom # 罗马尼亚语
  tr: tr # 土耳其语
  el: el # 希腊语
  hu: hu # 匈牙利语
  req-url: https://fanyi-api.baidu.com/api/trans/sdk/picture
  file-content-type: mutipart/form-data

cli:
  cli-style-id: 666
  get-qr-code-style-url: 666

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

domain:
  domain: 666

server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true